db = connect("localhost/csm");
db.placeAddresses.remove({});
db.placeAddresses.insert({ _id : NumberLong(1), street : "Шевченка", streetType : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(2), street : "Лесі Українки", streetType : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(3), street : "Івана Франка", streetType : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(4), street : "Івана Мазепи", streetType : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(5), street : "Степана Бандери", streetType : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(6), street : "Шевченка", streetType : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(7), street : "Лесі Українки", streetType : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(8), street : "Івана Франка", streetType : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(9), street : "Івана Мазепи", streetType : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(10), street : "Степана Бандери", streetType : "LANE"});